In [2]:
from __future__ import print_function
import torch

In [7]:
x = torch.empty(5, 3)
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9553, 0.5857, 0.2540],
        [0.2752, 0.0465, 0.3734],
        [0.7147, 0.4957, 0.8224],
        [0.3900, 0.9877, 0.9171],
        [0.5293, 0.7281, 0.7058]])


In [9]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.1247,  0.8621, -0.9584],
        [-0.3956, -0.2841, -0.3266],
        [ 0.4568, -0.3622, -0.9995],
        [ 0.1317, -0.3605,  0.4976],
        [-0.1230, -0.5414,  0.5040]])


In [13]:
print(x.size())

torch.Size([5, 3])


In [14]:
y = torch.rand(5,3)
print(x + y)

tensor([[-0.1740,  1.8077, -0.3015],
        [-0.0749,  0.1166, -0.2447],
        [ 1.4344,  0.1346, -0.1938],
        [ 0.8309, -0.1469,  1.3452],
        [ 0.0453, -0.0381,  0.8497]])


In [15]:
print(torch.add(x, y))

tensor([[-0.1740,  1.8077, -0.3015],
        [-0.0749,  0.1166, -0.2447],
        [ 1.4344,  0.1346, -0.1938],
        [ 0.8309, -0.1469,  1.3452],
        [ 0.0453, -0.0381,  0.8497]])


In [16]:
result = torch.empty(5,3)
torch.add(x, y, out = result)
print(result)

tensor([[-0.1740,  1.8077, -0.3015],
        [-0.0749,  0.1166, -0.2447],
        [ 1.4344,  0.1346, -0.1938],
        [ 0.8309, -0.1469,  1.3452],
        [ 0.0453, -0.0381,  0.8497]])


In [17]:
y.add_(x)
print(y)

tensor([[-0.1740,  1.8077, -0.3015],
        [-0.0749,  0.1166, -0.2447],
        [ 1.4344,  0.1346, -0.1938],
        [ 0.8309, -0.1469,  1.3452],
        [ 0.0453, -0.0381,  0.8497]])


In [18]:
print(x[:,1])

tensor([ 0.8621, -0.2841, -0.3622, -0.3605, -0.5414])


In [19]:
x = torch.randn(4,4)
y =x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [20]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-3.1111])
-3.111135244369507


In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device = device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

In [3]:
#AUTOGRAD
x = torch.ones(2,2,requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
print(y.grad_fn)

In [7]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [11]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [12]:
out.backward()

In [13]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [14]:
x = torch.randn(3, requires_grad=True)

y = x*2
while y.data.norm() < 1000:
    y = y * 2
    
print (y)

tensor([ -694.9879,   518.4492, -1100.5435], grad_fn=<MulBackward0>)


In [15]:
v = torch.tensor([0.1, 1.0, .0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [16]:
print(x.requires_grad)
print((x  ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [18]:
print(x.requires_grad)
y =  x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


In [20]:
#NEURAL NETWORKS
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16  * 6 * 6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return  x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [21]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [22]:
input = torch.randn(1,1,32,32)
out = net(input)
print(out)

tensor([[-0.0986, -0.0668,  0.0662, -0.0697, -0.0561, -0.0464, -0.0983, -0.0972,
         -0.1614, -0.0135]], grad_fn=<AddmmBackward>)


In [23]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [24]:
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)
criterion = nn.MSELoss()
loss = criterion(output, target)
print(loss)

tensor(0.4365, grad_fn=<MseLossBackward>)


In [28]:
print(loss.grad_fn)
print(loss.grad_fn.next_function[0][0])
print(loss.grad_fn.next_function[0][0].next_functions[0][0])
#error, does not run

AttributeError: 'MseLossBackward' object has no attribute 'next_function'

In [29]:
net.zero_grad()
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)
loss.backward()
print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([-0.0046,  0.0032, -0.0009, -0.0045, -0.0016,  0.0046])


In [30]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

In [31]:
import torch.optim as optim
optimizer = optim.SGD(net.parameters(), lr = 0.01)
optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()