In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -2.0000e+00,  0.0000e+00],
        [-2.0000e+00,  7.3836e-38,  4.5831e-41],
        [ 2.9287e-43,  0.0000e+00,  2.7746e-43],
        [ 0.0000e+00,  7.4002e-38,  4.5831e-41],
        [ 0.0000e+00, -2.0000e+00,  1.3264e-19]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7773, 0.5205, 0.8859],
        [0.7736, 0.2130, 0.1996],
        [0.7076, 0.9531, 0.7291],
        [0.2242, 0.2445, 0.0996],
        [0.3379, 0.6896, 0.9795]])


In [4]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1709, -0.2246, -0.0481],
        [-0.6086, -0.2526, -0.4807],
        [ 0.2707, -0.7880,  0.0193],
        [ 0.7888,  1.7958,  0.9592],
        [ 1.2542, -0.2420,  0.5460]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 0.0831,  0.3350,  0.7834],
        [-0.5164,  0.6953, -0.0742],
        [ 0.6753, -0.2390,  0.9863],
        [ 1.6021,  2.1452,  1.4355],
        [ 1.2872,  0.3782,  1.1064]])


In [9]:
print(torch.add(x, y))

tensor([[ 0.0831,  0.3350,  0.7834],
        [-0.5164,  0.6953, -0.0742],
        [ 0.6753, -0.2390,  0.9863],
        [ 1.6021,  2.1452,  1.4355],
        [ 1.2872,  0.3782,  1.1064]])


In [10]:
result = torch.empty(5,3)
torch.add(x, y, out = result)
print(result)

tensor([[ 0.0831,  0.3350,  0.7834],
        [-0.5164,  0.6953, -0.0742],
        [ 0.6753, -0.2390,  0.9863],
        [ 1.6021,  2.1452,  1.4355],
        [ 1.2872,  0.3782,  1.1064]])


In [11]:
y.add_(x)
print(y)

tensor([[ 0.0831,  0.3350,  0.7834],
        [-0.5164,  0.6953, -0.0742],
        [ 0.6753, -0.2390,  0.9863],
        [ 1.6021,  2.1452,  1.4355],
        [ 1.2872,  0.3782,  1.1064]])


In [12]:
print(x[:,1])

tensor([-0.2246, -0.2526, -0.7880,  1.7958, -0.2420])


In [13]:
x = torch.randn(4,4)
y =x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.9764])
1.9764090776443481


In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device = device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

In [20]:
#AUTOGRAD
x = torch.ones(2,2,requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [21]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [22]:
print(y.grad_fn)

In [23]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [24]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [25]:
out.backward()

In [26]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [27]:
x = torch.randn(3, requires_grad=True)

y = x*2
while y.data.norm() < 1000:
    y = y * 2
    
print (y)

tensor([-688.8309,   -0.7876,  772.4388], grad_fn=<MulBackward0>)


In [28]:
v = torch.tensor([0.1, 1.0, .0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [29]:
print(x.requires_grad)
print((x  ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [30]:
print(x.requires_grad)
y =  x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


In [31]:
#NEURAL NETWORKS
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16  * 6 * 6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return  x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [32]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [33]:
input = torch.randn(1,1,32,32)
out = net(input)
print(out)

tensor([[-0.0273, -0.0692,  0.0788, -0.0060,  0.0543,  0.0499, -0.0145, -0.0450,
          0.0526,  0.0166]], grad_fn=<AddmmBackward>)


In [34]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [35]:
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)
criterion = nn.MSELoss()
loss = criterion(output, target)
print(loss)

tensor(0.9412, grad_fn=<MseLossBackward>)


In [36]:
print(loss.grad_fn)
print(loss.grad_fn.next_function[0][0])
print(loss.grad_fn.next_function[0][0].next_functions[0][0])
#error, does not run

AttributeError: 'MseLossBackward' object has no attribute 'next_function'

In [37]:
net.zero_grad()
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)
loss.backward()
print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([ 0.0065,  0.0131, -0.0051,  0.0084, -0.0069, -0.0088])


In [38]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

In [39]:
import torch.optim as optim
optimizer = optim.SGD(net.parameters(), lr = 0.01)
optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()

In [40]:
#TRAINING A CLASSIFIER
import torch
import torchvision
import torchvision.transforms as transforms

In [41]:
transform = transforms.Compose(
    [transforms.ToTensor(), 
    transforms.Normalize((0.5,0.5,0.5), (0.5,0.5,0.5))])
trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                       download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                         shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                      download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                        shuffle=False, num_workers=2)
classes = ('plane', 'car', 'bird', 'cat', 
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

Files already downloaded and verified
Files already downloaded and verified


In [42]:
import matplotlib.pyplot as plt
import numpy as np
def imshow(img):
    img = img/2 + .5
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1,2,0)))
    plt.show()
    
    dataiter = iter(trainloader)
    images, labels = dataiter.next()
    imshow(torchvision.utils.make_grid(images))
    print(' '.join('%5s' % classes[labels[j]] for j in range(4)))
    #no output is shown, contrary to the tutorial

In [43]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(R.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    net = Net()

In [44]:
import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr = .001, momentum = .9)


In [45]:
for epoch in range(2):
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        if i % 2000 == 1999:
            print('[%d, %5d] loss: %.3f' %
                 (epoch + 1, i + 1, running_loss/2000))
            running_loss = .0
        
print('Finished Training')
#Runtime error occurs: rest of this section of tutorial from here is dependent on having this model work, 
#so I am skipping to the data parallelism section

RuntimeError: Given groups=1, weight of size 6 1 3 3, expected input[4, 3, 32, 32] to have 1 channels, but got 3 channels instead

In [46]:
#OPTIONAL: DATA PARALLELISM
import torch 
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

input_size = 5
output_size = 2
batch_size = 30
data_size = 100


In [47]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [49]:
class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)
        
    def __getitem__(self, index):
        return self.data[index]
    
    def __len__(self):
        return self.len
    
rand_loader = DataLoader(dataset=RandomDataset(input_size, data_size),
                        batch_size = batch_size, shuffle = True)

In [52]:
class Model(nn.Module):
    
    def __init__(self, input_size, output_size):
        super(Model, self).__init__()
        self.fc = nn.Linear(input_size, output_size)
        
    def forward(self, input):
        output=self.fc(input)
        print("\tIn Model: input size", input.size(),
             "outpu size", output.size())
        return output

In [53]:
model = Model(input_size, output_size)
if torch.cuda.device_count() > 1:
    print("Let's use", torch.cuda.device_count(), "GPUs!")
    model = nn.DataParallel(model)
    
model.to(device)

Model(
  (fc): Linear(in_features=5, out_features=2, bias=True)
)

In [55]:
for data in rand_loader:
    input = data.to(device)
    output = model(input)
    print("Outside: input size", input.size(),
         "output_size", output.size())

	In Model: input size torch.Size([30, 5]) outpu size torch.Size([30, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
	In Model: input size torch.Size([30, 5]) outpu size torch.Size([30, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
	In Model: input size torch.Size([30, 5]) outpu size torch.Size([30, 2])
Outside: input size torch.Size([30, 5]) output_size torch.Size([30, 2])
	In Model: input size torch.Size([10, 5]) outpu size torch.Size([10, 2])
Outside: input size torch.Size([10, 5]) output_size torch.Size([10, 2])
